### ISSUE TITLE
Please keep signing v1

### ISSUE THREAD

**Issue by IzzySoft** [sergiopatricio/Scrum-Cards#10]
The APK attached to v2.5 lacks v1 signature; `apksigner` reports:

```
Verified using v1 scheme (JAR signing): false
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
```

That means this APK cannot be used for Android versions before 7, as those do not understand v2 signatures (and I'm not 100% sure for Android 7; v2 could well have been introduced with Android 8). Could you please keep signing v1 along (and replace the v2.5 APK with a properly signed one)? Thanks!

**Comment by sergiopatricio** [comment]
Hi, I think v2 can be used in Android 7.0 https://source.android.com/security/apksigning/v2#verification

I forgot to mention in the release, I updated the minimum SDK required for Android 7.0, so the 2.5 release should not work on previous android releases. The reason for this was that there are no many active installations on previous versions and I didn't find a good reason to keep maintaining those versions.

2.4 is still available on the google store for older versions of Android.

**Comment by IzzySoft** [comment]
One more reason for v1 sig is: I can not update it in my repo without it as fdroidserver won't take it:

```
ERROR: No signing certificates found in repo/pt.samp.scrumCards_2.5.apk
WARNING: Skipping 'pt.samp.scrumCards_2.5.apk' with invalid signature!
```

**Comment by sergiopatricio** [comment]
APK updated, please try now.

**Comment by IzzySoft** [comment]
Sorry, still no v1 sigs there:

```
Verified using v1 scheme (JAR signing): false
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
```

Looking inside the file: no certs in `META-INF`.

**Comment by sergiopatricio** [comment]
I will have to investigate. It may be because of the minimum Android version set to 7.0. Since it's not needed it may be ignored if I tell Android Studio to add it.

**Comment by IzzySoft** [comment]
Ugh, that might indeed be the reason. Thanks for caring! I'll check whether there's already a corresponding issue open with fdroidserver (and if not, create one). Lack of v1 should not lead to the package being ignored in this case.

[Done that](https://gitlab.com/fdroid/fdroidserver/issues/703). But even if accepted, it might take a while until implemented there due to lack of man-power…

**Comment by IzzySoft** [comment]
OK, issue solved on my end via an update (or rather addition) to my fdroidserver install. v2-only will now be processed correctly – thanks to 102 MB "stuff installed" :scream: (dependencies are sometimes a crux: I don't need all those fonts…).

Thanks for your patience! So if support for Android < 7 is dropped anyway, v1 sig will no longer be needed. Scrum Cards 2.5 was successfully accepted by fdroidserver here, and goes live in my repo with the next sync (in about 20h from now).
