### ISSUE TITLE
Attach APK to release?

### ISSUE THREAD

**Issue by IzzySoft** [sergiopatricio/Scrum-Cards#6]
Would you mind attaching the `.apk` file to the `releases/` for those folks without GPlay access? Thanks in advance!

**Comment by sergiopatricio** [comment]
@IzzySoft the `.apk` files were under the `publish` folder. Not really a good name, so I renamed the folder to `releases` now.

**Comment by IzzySoft** [comment]
OK, that's another way, thanks! Though I rather thought of the [`releases/` page](https://github.com/sergiopatricio/Scrum-Cards/releases) – which is where most projects have them. That's the most obvious place, and one doesn't have to checkout all the binaries when cloning the repo.

In case you're not familiar with that part of Github, [a short howto](https://help.github.com/articles/creating-releases/) is part of the Github help pages. Would be preferable to have the releases there (for users not that familiar with Github it's easier to pick them from that page, where the files would be directly downloaded and you even can place a description along (e.g. a short Changelog) – while from inside the repo, Github tries to "display" them). But of course the most important part is to get them at all :)

So thanks again!

**Comment by sergiopatricio** [comment]
Thanks, was not aware of this particular feature of Github. Now I realize that I have seen the releases page for other projects but didn't remember to have it my project.

**Comment by IzzySoft** [comment]
*LOL* Yeah, such things happen. And we learn new things everyday :) So I guess you'll go this path and attach `.apk` files for (the latest current and) new releases there?

**Comment by sergiopatricio** [comment]
Yes, already added.

**Comment by IzzySoft** [comment]
Thanks a lot!
